apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-bank-app
  labels:
    app: my-bank-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-bank-app
  template:
    metadata:
      labels:
        app: my-bank-app
    spec:
      containers:
      - name: my-bank-app
        image: krishwuds/my-bank-app-cicd:replaceimagetag
        ports:
        - containerPort: 8080
